name: 'Build and Test Eclipse Installation Manager'

on:
  workflow_dispatch:
  push:
    branches:
     - 'feature/*'
     - 'bugfix/*'
  pull_request:
    branches:
     - 'main'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
        fetch-depth: 1
     - 
      name: Build application, run tests and create coverage reports
      id: script
      run: |
        /bin/bash ${GITHUB_WORKSPACE}/buildAndTest.sh
     - 
      name: version
      run: echo "::set-output name=version::$(cat version)"
      id: version
     -
      name: Release build artifact
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
     - name: upload implementation artifact
       uses: actions/upload-release-asset@v1
       env:
        GITHUB_TOKEN: ${{ github.token }}
       with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./eim/generated/distributions/executable/eim.jar
        asset_name: eim.jar
        asset_content_type: application/java-archive
     - name: upload api artifact
       uses: actions/upload-release-asset@v1
       env:
        GITHUB_TOKEN: ${{ github.token }}
       with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./eim.api/generated/distributions/executable/eim.api.jar
        asset_name: eim.jar
        asset_content_type: application/java-archive